version: "3.3"
services:
  web:
    restart: always
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./:/home/flask/app/
    depends_on:
      - redis
    links:
      - redis
      
  redis:
    restart: always
    image: redis:6.2-alpine

  test:
    image: curlimages/curl:7.73.0
    command: /bin/sh -c "sleep 10 && curl -s http://web:5001/ -i -vvv"
    depends_on:
      - web

